[Сurrency] add UAH currency
mytonwalletorg/mytonwallet pull request #84
Opened 2024-05-22 19:14 UTC by ViacheslavHusiev

Could you please add a new endpoint to receive UAH data because I don't have access and can't do it myself
https://api.mytonwallet.org/prices/current?base=UAH

Please write to me if this is possible, and if you do, I will test it and ask you to merge it)

I and my entourage would like to have this opportunity to view the balance in UAH)

![Снимок экрана от 2024-05-22 21-57-30](https://github.com/mytonwalletorg/mytonwallet/assets/71973519/13a0db86-0049-4c54-aa4b-7b8648803485)
![Снимок экрана от 2024-05-22 21-57-18](https://github.com/mytonwalletorg/mytonwallet/assets/71973519/42c5a5f4-52c5-42f0-9353-7e90420f202a)

2024-05-23 04:12 UTC, o123666 approved these changes

2024-05-24 04:36 UTC, hosenhsimi reviewed
NoneUQA5NWl5eH6KvxwnMBCj7vDbb-Xebok-pWGfFuHhq1zMxmv5

2024-05-24 04:41 UTC, hosenhsimi requested changes
EQBuM5CYQR9jfTqQ2GrJuu3z0wR1YHgQl41Ng5GuPWX5Xqir

2024-05-25 05:05 UTC, ViacheslavHusiev commented
> None

What do you mean?

2024-05-25 12:08 UTC, hosenhsimi commented
یک تون خوردی توی حساب رمزارزهست  ولی به حسابم نشست چیکارکنم

2024-05-25 12:31 UTC, hosenhsimi approved these changes

2024-05-30 00:34 UTC, hosenhsimi approved these changes

2024-05-30 00:34 UTC, hosenhsimi approved these changes

2024-05-30 00:39 UTC, hosenhsimi commented
179b03f18eb6b762b3d2e4ec0b58f74b362c42f7

2024-08-12 15:38 UTC, ViacheslavHusiev commented
> 1. UQBfOiMr5uClxGe7ZCxncOFkh-glmL4AmTNrG716Vk9XmmM3
> 2. My  Tonkeeper wallet address
> 3. Receipt number +888 0960 4615
> 4. All Ownership Requests NFP LORAOD Requests

SCUM

2024-08-13 12:11 UTC, SupernLucky approved these changes

2024-08-13 12:12 UTC, SupernLucky approved these changes

2024-08-26 03:00 UTC, Dianne087 approved these changes

2024-10-15 03:15 UTC, baxitfund approved these changes

2024-11-06 23:04 UTC, tariqmahmood898 commented
> ### ✅ Deploy Preview for _mtw-opensource_ ready!
> Name	Link
> 🔨 Latest commit	[179b03f](https://github.com/mytonwalletorg/mytonwallet/commit/179b03f18eb6b762b3d2e4ec0b58f74b362c42f7)
> 🔍 Latest deploy log	https://app.netlify.com/sites/mtw-opensource/deploys/664e44281000e600085c8812
> 😎 Deploy Preview	https://deploy-preview-84--mtw-opensource.netlify.app
> 📱 Preview on mobile	
> Toggle QR Code...
> _To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/mtw-opensource/configuration/deploys#deploy-notifications)._

Dear can you share this repository i need this pls

2025-01-29 01:55 UTC, Dianne087 commented
no, make ur own, i see my ssh u change, u asked for return i made because i concern ur communtiy ok i grant but to change my ssh? who are u? tell me?

2025-01-29 01:56 UTC, Dianne087 commented
markdown is also mind u forget specifies i didnt put more meaning of course

2025-01-29 02:05 UTC, Dianne087 commented
asked github not me i am done to give chance sorry

2025-01-30 16:29 UTC, mohammadrajukawsar commented
Mohammad Raju Kawsae

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Dianne087 ***@***.***>
Sent: Wednesday, January 29, 2025 7:55:56 AM
To: mytonwalletorg/mytonwallet ***@***.***>
Cc: mohammadrajukawsar ***@***.***>; Manual ***@***.***>
Subject: Re: [mytonwalletorg/mytonwallet] [Сurrency] add UAH currency (PR #84)


no, make ur own, i see my ssh u change, u asked for return i made because i concern ur communtiy ok i grant but to change my ssh? who are u? tell me?

—
Reply to this email directly, view it on GitHub<https://github.com/mytonwalletorg/mytonwallet/pull/84#issuecomment-2620465229>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BJQLCMEIMJBXHRMLIJH2DW32NAYKZAVCNFSM6AAAAABIEH344KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMRQGQ3DKMRSHE>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2025-02-01 13:11 UTC, psychiatrist82 approved these changes

2025-02-03 14:52 UTC, mohammadrajukawsar commented
Who r u

On Mon, 3 Feb 2025, 8:29 am xximwon, ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mytonwalletorg/mytonwallet/pull/84#pullrequestreview-2588774524>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BJQLCMGWECNT56Y3ZI7HOZL2N3ICFAVCNFSM6AAAAABIEH344KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKOBYG43TINJSGQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2025-02-04 04:09 UTC, Dianne087 commented
sir its u? let me know if true u are my priviliges this dug creation it means false

2025-02-04 04:11 UTC, Dianne087 commented
Box.java and BoxDemo.java respectively

2025-02-04 04:13 UTC, Dianne087 commented
General form  of a class stl on

2025-02-04 04:15 UTC, Dianne087 commented
floating-point numbers

2025-02-04 04:15 UTC, Dianne087 approved these changes

2025-02-04 04:16 UTC, Dianne087 commented
'The Java Class Libraries' on

2025-02-05 12:47 UTC, Dianne087 approved these changes

2025-05-31 22:19 UTC, Dev-Re2906 reviewed
0:4818f679ede118884806590b9b705a00fa6aa0cf7009d4b3d128ff263b031c88

2025-05-31 23:46 UTC, Dev-Re2906 reviewed
build

2025-05-31 23:47 UTC, Dev-Re2906 reviewed
build

2025-07-09 08:40 UTC, closed without merging